# Collection settings
collections:
  md_pages:
    output: true
  galleries: {}
  posts:
    permalink: /:categories/:title
  showcases: {}
  filterable_tags: {}

# Build settings
destination: _site
markdown: kramdown
kramdown:
  header_offset: 3
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Prevent from clobbering.
# Netlify CMS assets are created before Jekyll build via Rake build
# task.
keep_files:
  - assets/javascripts/cms.js
  - assets/javascripts/cms.js.map
  - assets/stylesheets/cms.css
  - assets/src
  - assets/node_modules
  - media
