# Site settings
title: Vydry online
description: >-
  Aktuální a komplexní informace o vydře říční a projektu Realizace
  vybraných opatření pro vydru říční v České republice.
baseurl: ""
url: https://www.vydryonline.cz
author: alka-wildlife

# Integrations and machine-readable metadata
facebook:
  app_id: 145375228868712
  publisher: 269120446533000
  admins: 1133305906
logo: "/uploads/vydry_online_green.png"
social:
  name: ALKA Wildlife, o.p.s.
  links:
    - https://www.facebook.com/AlkaWildlife
webmaster_verifications:
  google: o27dsTgYww0bzXVmTZ_CgadoY8QtzpDMgo-bVSgH3OM
lang: cs-CZ
google_analytics: UA-57533252-3

# Collection settings
collections:
  md_pages:
    output: true
  galleries: {}
  posts:
    output: true
    permalink: "/news/:title"
  showcases: {}
  user_answers:
    output: true
    permalink: "/user-answers/:title"
  filterable_tags: {}
  photos: {}

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: user_answers
    values:
      layout: user_answer

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - Rakefile
  - rakelib
  - bin

# Prevent from clobbering.
# Netlify CMS and Netlify Identity Widget assets are created before
# Jekyll build via Rake build task.
keep_files:
  - assets/javascripts/cms.js
  - assets/javascripts/cms.js.map
  - assets/stylesheets/cms.css
  - assets/javascripts/netlify-identity-widget.js
  - assets/javascripts/netlify-identity-widget.js.map
